apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa 
  namespace: default
roleRef:
  kind: Role 
  name: sa-role 
  apiGroup: rbac.authorization.k8s.io
