apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sa-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - pods
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
